chpladmin/chpl-website

README.md, app/app.css, app/app.js, app/appDev.js, app/index.html, app/login/login_test.js, app/nav/layouts/privacy.html, app/nav/nav-bottom.html, app/nav/nav-top.html, app/nav/navCtrl.js, app/nav/nav_test.js, app/search/search.html, app/search/searchCtrl.js, app/search/searchModule.js, app/search/searchService.js, app/search/search_test.js, app/view1/view1.html, app/view1/view1.js, app/view2/view2.js, bower.json, e2e-tests/scenarios.js, karma.conf.js
Framework is set up; website is ready to be developed
=> OCD 129: 508 framework compliance

app/appDev.js, app/login/loginServices.js, app/nav/nav-top.html, app/nav/navCtrl.js, app/nav/navModule.js, app/nav/nav_test.js
Authentication connected. Calls /auth/authenticate end point, and then displays data only available to authenticated users by calling /auth/list_users end point
=> Ocd 144 - wire up authentication

app/admin/components/vpManagementDirective.js, app/admin/components/vpManagementDirective_test.js, app/api/api.html, app/api/apiCtrl.js, app/api/apiModule.js, app/api/apiService.js, app/api/api_test.js, app/apiDefinition.js, app/app.js, app/appDev.js, app/common/components/certsDirective.js, app/common/components/certsDirective_test.js, app/index.html, karma.conf.js, package.json
Documentation screen built. API calls defined in code. If there's a way to pull the definitions as an API call, we'd be able to drop the definitions here. Until then (if ever) the definitions are here.
=> Ocd 153 - Admin API documentation

RELEASE_NOTES.md, app/admin/admin.html, app/admin/components/vpManagement.html, app/api/api.html, app/overview/overview.html, app/search/searchCtrl.js
* Disabled non-functional sections of website
=> Version 0.0.2

RELEASE_NOTES.md, app/admin/components/reportsDirective.js, app/admin/components/vpEditProduct.html, app/admin/components/vpEditProductCtrl.js, app/admin/components/vpManagementDirective.js, app/admin/components/vpMergeProduct.html, app/admin/components/vpMergeProductCtrl.js, app/common/commonService.js, app/compare/compare.html, app/product/product.html, app/resources/resources.html
Covers OCD-975, OCD-976, OCD-977
=> UI for Previous Owners of a product

app/search/search.css, app/search/search.html, app/search/searchCtrl.js, app/search/search_test.js
Not ready for push to STG yet, but want to give people a chance to look at the current status; needs API push as well. @dlucas1 & @kekey1, please review and approve/request changes, but leave it for me to merge it in when it's approved, as I'm the one who'll push it to DEV
=> Ocd 997 - Filters

RELEASE_NOTES.md, app/search/search.css, app/search/search.html
Fixed filter link label stuff. Ready for DEV, likely ready for STG
=> OCD-997: Filters complete (as to functionality)

app/admin/components/vpMergeProductCtrl.js, app/app.css, app/common/utilService.js, app/common/util_test.js, app/compare/compareCtrl.js, app/compare/compare_test.js, app/search/search.css, app/search/search.html, app/search/searchCtrl.js, app/search/search_test.js
* Better text
* Better sorting of CQMs/Criteria
* Collapsible 'more' elements
* Smaller Developer/Product/Version boxes
* General color scheme updates
=> OCD-997: Filter improvements

app/admin/components/cp/vpManagement.html, app/admin/components/cp/vpManagementDirective.js, app/app.css, app/common/components/smart_table/stCustomFilter.js, app/common/components/smart_table/stDateRange.html, app/common/components/smart_table/stDateRange.js, app/common/components/smart_table/stNumberRange.js, app/decertifications/products/products.html, app/decertifications/products/productsCtrl.js, app/decertifications/products/productsCtrl_test.js
* Fixed date-range filter on Decertified Developers
* Added Surveillance Activity searching
=> EOA improvements

RELEASE_NOTES.md, app/admin/components/cp/vpManagement.html, app/admin/components/cp/vpManagementDirective.js, app/common/commonModule.template, app/common/components/cap.html, app/common/components/capDirective.js, app/search/searchCtrl.js, app/search/search_test.js, bower.json
Requires addition of a line to the <templated> commonModule.js file
=> OCD-1069: Add parameter for enabling CAP modification/addition

app/admin/adminCtrl.js, app/admin/components/cp/vpEditCertifiedProduct.html, app/admin/components/surveillance/editNonconformity.html, app/admin/components/surveillance/editRequirement.html, app/admin/components/surveillance/editSurveillance.html, app/common/components/smart_table/stNumberRange.html
* Fixed mis-required SED end date on CP Edit
* Stored comment for how to use st-number-range directive
=> OCD-1013: Update reporting routing

app/admin/admin.css, app/admin/components/cms.html
* added stylesheet formatting for CMS Management page
* made file upload table responsive based on width of browser (shows horizontal scrollbar if page width is reduced and stays within width of main-content border
=> OCD-1019: added stylesheet formatting to CMS Management page and made file uploader responsive to page width

app/admin/components/surveillance/editSurveillanceCtrl.js, app/common/components/certificationCriteria/certs.html, app/common/components/surveillance/surveillance.html, app/common/components/surveillance/surveillanceDirective.js
Fixes issue with creating non-conformities in new surveillances of the wrong edition; re-orders requirements on CP details page
=> Surveillance view/create mods

src/app/components/certificationCriteria/certificationCriteria.directive.js
Fixes issue @dlucas1 found yesterday
=> OCD-1074: Allow editing of certification criteria again

RELEASE_NOTES.md, src/app/index.run.js, src/app/search/search.controller.js, src/app/search/search.controller.spec.js
Think this is working though I'm having trouble getting the webapp to run (heap size caching issues). Working through that, but the icon/new status shows up on the /search page correctly
=> OCD-1137: Added status: withdrawn by developer under surveillance/review

RELEASE_NOTES.md, bower.json, src/app/admin/components/cms/cms.directive.js, src/app/admin/components/cms/cms.directive.spec.js, src/app/admin/components/cms/cms.html, src/app/admin/components/reports/reports.html, src/app/common/common.service.js, src/app/decertifications/developers/developers.controller.js, src/app/decertifications/developers/developers.controller.spec.js, src/app/decertifications/developers/developers.html, src/app/decertifications/products/products.controller.js, src/app/decertifications/products/products.controller.spec.js, src/app/decertifications/products/products.html, src/app/index.module.js, src/app/navigation/navigation-top.html, src/app/search/search.controller.js
* Added "Meaningful Use Users Accurate As Of Date value
* CMS Management allows editing
* Decertified Developers/Products displays
* Update ui-bootstrap to use font-awesome icons
* Fixed reports ACB -> ONC-ACB
* Renamed decertified developers on nav bar
* Defaulted criteria filter to folded shut
=> OCD-1160: MUU Accurate date + UI tweaks

RELEASE_NOTES.md, src/app/components/cms_widget/cms_widget_button.html, src/app/decertifications/developers/developers.controller.js, src/app/decertifications/developers/developers.controller.spec.js, src/app/decertifications/developers/developers.html, src/app/decertifications/products/products.controller.js, src/app/decertifications/products/products.controller.spec.js, src/app/index.scss, src/app/navigation/navigation-top.html, src/app/navigation/navigation.directive.js, src/app/navigation/navigation.directive.spec.js, src/app/search/search.controller.js, src/app/search/search.controller.spec.js, src/app/search/search.html
* Rearranged navigation
* Changed default filters to "Active" or "Suspended by..." only
* Changed Suspended Developer page text
* Integrated with screenshot of API for accurate_as_of
=> Various tweaks (mostly cosmetic)

RELEASE_NOTES.md, bower.json, src/app/admin/admin.module.js, src/app/admin/components/certifiedProduct/vpEditCertifiedProduct.controller.js, src/app/admin/components/certifiedProduct/vpManagement.directive.js, src/app/admin/components/cms/cms.directive.js, src/app/admin/components/cms/cms.directive.spec.js, src/app/index.module.js, src/app/navigation/navigation.directive.spec.js, src/app/navigation/navigation.module.js, src/index.html
* OCD-1165: pop-up notification if CHPL Product Num changes
* OCD-1148: Integrate with API
=> Popup notification & muuAccurateAsOfDate integration

RELEASE_NOTES.md, src/app/admin/admin.html, src/app/admin/components/atl/atlEdit.html, src/app/admin/components/atl/atlManagement.html, src/app/admin/components/reports/reports.directive.js, src/app/admin/components/reports/reports.html, src/app/navigation/navigation-top.html, src/app/overview/overview.html
Redo OCD-1167
This reverts commit 9f4e185dfac933974808335e9e78d914579e47e5.
=> Revert "OCD-1182: ONC-ATL -> ATL"

src/app/components/certificationStatus/certificationStatus.html, src/app/components/cms_widget/cms_widget.directive.js, src/app/navigation/navigation.scss
Some CSS tweaks & page text changes wanted by the customer in here too
=> OCD-1156: Fix certId so it doesn't conflict with OBE widget

RELEASE_NOTES.md, src/app/admin/components/surveillance/editNonconformity.controller.js, src/app/admin/components/surveillance/editNonconformity.controller.spec.js, src/app/admin/components/surveillance/editNonconformity.html
Only deploying to development since staging is frozen until Wednesday 3/29.
=> OCD-1329: initiate/edit/add nonConformity requires CAPMustCompleteDate when entry for CAPApprovalDate

RELEASE_NOTES.md, src/app/components/smart_table/aiSurveillanceFilter.js, src/app/decertifications/nonconformities/nonconformities.controller.js, src/app/index.scss, src/app/search/search.html
* OCD-1345: Removed 2011 from filter in NCs page
* OCD-1224: Reset surveillance filter on "view previously" filters
* Added "ONC-" to search box IAW policy
=> OCD-1400: Made surveillance activity a main filter

RELEASE_NOTES.md, src/app/components/smart_table/aiCustomFilter.js, src/app/components/smart_table/stListMultiple.js, src/app/search/search.controller.js, src/app/search/search.html
* OCD-994: Added "previous developers" to Developer filter
=> OCD-1414: CQM filter bug fix

RELEASE_NOTES.md, features/pages/angularPage.js, features/step_definitions/testStepDefinitions.js, features/support/chai.js, features/support/hooks.js, features/support/world.js, features/test.feature, gulp/conf.js, gulp/e2e-tests.js, package.json, protractor.conf.js, src/app/admin/components/certifiedProduct/vpManagement.directive.js, src/app/admin/components/certifiedProduct/vpManagement.directive.spec.js, src/app/components/certificationCriteria/certs.directive.js, src/app/components/certificationCriteria/certs.directive.spec.js
There's some stuff in here for setting up BDD stuff. That can mostly be ignored for now
=> Filtered test functionalities

.gitignore, RELEASE_NOTES.md, features/components/admin/admin.feature, features/components/admin/admin.login.steps.js.template, features/components/admin/admin.page.js, features/components/admin/admin.steps.js, src/app/decertifications/nonconformities/nonconformities.html, src/app/decertifications/products/products.html
Has some e2e stuff in there that's in "work in progress" status
=> Text changes for Nonconformites & Decertified Products pages

src/app/collections/apiDocumentation/apiDocumentation.html, src/app/collections/nonconformities/nonconformities.html, src/app/index.route.js, src/app/navigation/navigation-top.html, src/app/product/product.scss, src/app/search/search.html
* OCD-1359: Rearranged nav bar, changed names of things
* OCD-1350: Changed name
=> Navigation & API Documentation changes

gulp/server.js, src/app/admin/components/certifiedProduct/listing/edit.html, src/app/admin/components/certifiedProduct/management.html, src/app/components/certificationCriteria/certs.html
=> ICS tweaks

RELEASE_NOTES.md, src/app/navigation/navigation.directive.js, src/app/navigation/navigation.directive.spec.js, src/app/navigation/navigation.module.js, src/app/navigation/navigation.module.spec.js
Also beefed up navigation module test coverage
=> OCD-1341: Add toaster when Admin does something to evict Listing cache

RELEASE_NOTES.md, src/app/resources/download/download.controller.js, src/app/resources/download/download.html
This reverts commit c3235a897dfc861fbd3b4672f38d175776d87cd9.
=> Revert "OCD-1770: Put "complete listing" back in; marked as deprecated"

RELEASE_NOTES.md, src/app/collections/sed/sed.controller.js, src/app/collections/sed/sed.html
@brianlindsy I tweaked the button placement a bit. @kekey1 I don't know if you saw this PR from Brian; he'd accidentally PR'd it to my fork.
=> SED Download all button

RELEASE_NOTES.md, src/app/admin/components/certifiedProduct/listing/edit.controller.js, src/app/admin/components/certifiedProduct/listing/edit.controller.spec.js, src/app/admin/components/certifiedProduct/listing/edit.html
PR'ing this, though won't merge it until DEV gets the API requirement and that's QA'd. Had thought to put UI on STG & API on DEV, but that won't work.
=> OCD-1871: Require ICS Source for 2015 Listings with ICS=true during edit

src/app/components/listing_details/details.html, src/app/components/listing_details/sed/sed.html
@ashwinimore I did not exactly match what you'd put in the ticket. The new IDs do relate to the old ones (and have the same format) so please take a look
=> OCD-1941: Addition of some more ID fields for AQA

PENDING_RELEASE_NOTES.md, gulp/html-lint.js, src/app/index.scss, src/error.html, src/index.html, src/style.html
* Enable setting up automated deployment
Not sure if this should go to DEV before the freeze; leaning towards yes, but on the fence
=> OCD-2198: Create basic error page

src/app/admin/components/certifiedProduct/product/edit.controller.spec.js
=> Fixed unit test

PENDING_PENDING_RELEASE_NOTES.md, src/app/components/listing_details/criteriaModal.html
=> Filtered 2014 test functionality by practice type and cert criterion

src/app/admin/components/reports/reports.directive.js
=> Fixed issue with Test Functionality diaplying on Activty Report

src/app/admin/components/certifiedProduct/listing/edit.html, src/app/admin/components/certifiedProduct/listing/inspect.html
=> Add ids during confirm workflow

gulp/inject.js
[#chore]
Need this approved and deployed before the next DEV plan runs
=> Fix build script to include appropriate HTML files

package.json, webpack.config.js, webpack.dev.js, webpack.prod.js
=> Add DEV/STG environments to webpack configs

src/app/admin/components/certifiedProduct/developer/edit.controller.js, src/app/admin/components/schedules/job.controller.js, src/app/admin/components/schedules/job.controller.spec.js
=> Handle jobs with editable fields but without data

src/app/admin/components/certifiedProduct/management.html
=> Add missing ID to support AQA

src/app/components/listing_details/criteria.html
=> Fix QMS tooltip; add SED one

PENDING_PENDING_RELEASE_NOTES.md, package.json, src/app/admin/admin.controller.js, src/app/admin/admin.controller.spec.js, src/app/admin/admin.html, src/app/admin/admin.module.js, src/app/admin/components/login/login.directive.js, src/app/admin/components/login/login.directive.spec.js, src/app/admin/components/login/login.html, src/app/components/contact/contact.html, src/app/index.js, src/app/navigation/navigation-bottom.html, src/app/navigation/navigation.directive.js, src/app/navigation/navigation.directive.spec.js, src/app/registration/create-user.html, src/app/registration/create.controller.js, src/app/registration/create.controller.spec.js, src/app/services/login.service.js, src/app/services/login.service.spec.js, src/app/services/network.service.js, src/app/services/network.service.spec.js, src/app/services/util.service.js, src/app/services/util.service.spec.js, yarn.lock
[#OCD-1310]
Needs to be deployed so QA can check the API strength stuff. Will be enhanced later with front-end password checking, hence no RELEASE NOTES
=> Remove password validation check; display strength values from API

PENDING_PENDING_RELEASE_NOTES.md, src/app/search/search.html
=> Add Developer Status to search results page

src/app/components/listing_details/criteriaModal.controller.js
[#OCD-2499]
No release notes as this never actually got to PROD, so no end user impact
=> Re-enable certification criteria editing

src/app/product/history/history.controller.spec.js
=> Ignore test failure due to timezone temporarily

src/app/product/history/history.controller.js, src/app/product/history/history.controller.spec.js
=> Handle listings w/o MUU history in eye

src/app/services/network.service.js, src/app/services/network.service.spec.js
=> Use correct verb for Listing update

src/app/product/history/history.controller.js, src/app/product/history/history.controller.spec.js
=> Show change of MUU history when only one item

src/app/registration/components/apiKey.html, src/app/services/network.service.js, src/app/services/network.service.spec.js
=> Send blank for add_role; fix some typos

PENDING_RELEASE_NOTES.md, src/app/registration/create-user.html
=> Apply maxlength validator to username

src/app/services/network.service.js, src/app/services/network.service.spec.js
=> Update "reject" endpoints wrt API

src/app/registration/create-user.html
=> Display username too long error at bottom of page

src/app/services/network.service.js
=> Allow DELETE calls with body data

src/app/admin/components/surveillance/nonconformity/edit.html
=> Disable "save" button when site counts are bad

src/error.html, src/index.html
[#OCD-2594]
No release notes for this one as there's nothing visible to an end user
=> refactor: add new google analytics container

PENDING_RELEASE_NOTES.md, src/app/services/network.service.js, src/app/services/network.service.spec.js
=> fix: use correct endpoint to register an API key

src/app/components/listing_details/criteria.component.js, src/app/components/listing_details/details.directive.js, src/app/components/listing_details/details.html
=> fix: re-enable editing of certification criteria

PENDING_PENDING_RELEASE_NOTES.md, src/app/admin/admin.controller.js, src/app/admin/admin.html, src/app/admin/components/acb/view.component.js, src/app/admin/components/atl/view.component.js, src/app/admin/components/atl/view.html
=> fix: fix navigation related to ATL management

src/app/admin/components/surveillance/edit.html, src/app/admin/components/surveillance/inspect.html, src/app/components/surveillance/surveillance.html
=> fix: display the correct surveillance authority

src/app/components/listing_details/details.html
=> refactor: add ids that can be used for AQA in listing details

src/app/components/surveillance/surveillance.component.js
=> fix: re-enable editing of surveillance

src/app/components/listing_details/criteriaModal.controller.js
=> feat: disable test tools when ics=false and retired=true

src/app/components/listing_details/criteriaModal.controller.spec.js
=> test: fix tests for disabled tools

src/app/services/login.service.js
=> feat: enable UI restriction on impersonation

src/app/admin/components/login/login.directive.js, src/app/registration/create.controller.js
=> fix: tweak display of "stop impersonating"

src/app/index.route.js, webpack.ci.js, webpack.dev-prod.js, webpack.dev.js, webpack.prod.js
[#OCD-2757, OCD-2756, OCD-2758]
=> build: separate DEV_MODE and UAT_MODE

src/app/admin/components/reports/reports.listing.html, src/app/components/listing-details/details.directive.js, src/app/components/listing-details/ics-family/ics-family-modal.controller.js
=> fix: put more details in download file

src/app/admin/components/reports/reports.listing.component.js, src/app/admin/components/reports/reports.listing.html
=> fix: support Edge with filter

src/app/admin/components/certifiedProduct/management.html
=> fix: allow selection of developers on confirm

PENDING_RELEASE_NOTES.md, src/unsupported-browser.html, webpack.config.js
=> feat: redirect users using unsupported browsers

src/app/admin/components/certifiedProduct/management.html, src/app/components/developer/developer.html, src/app/components/product/product.html, src/app/components/version/version.html, src/app/pages/organizations/developers/developers.html, src/app/pages/organizations/developers/products/products.html, src/app/pages/organizations/developers/products/versions/versions.html
=> test: add IDs to support AQA tests

src/app/admin/components/reports/reports.component.spec.js, src/app/admin/components/reports/reports.listing.component.js, src/app/admin/components/reports/reports.listing.component.spec.js, src/app/admin/components/reports/reports.service.js
=> test: fix broken unit tests

src/app/components/version/version.html
=> #OCD-2758 fix: use correct ID

src/app/components/developer/developer.html, src/app/components/product/product.html, src/app/components/version/version.html, src/app/pages/organizations/developers/products/products.html, src/app/pages/organizations/developers/products/versions/versions.html
=> feat: update headings & page layout

PENDING_RELEASE_NOTES.md, src/app/pages/listing/listing.component.js, src/app/pages/listing/listing.component.spec.js, src/app/pages/listing/listing.html
=> [#OCD-2822] feat: show history popup for all listings

src/app/components/developer/developer.html, src/app/components/product/product.html, src/app/components/version/version.html
[#OCD-2756, #OCD-2757, #OCD-2758]
=> feat: add code and last modified dates where appropriate

src/app/index.route.js, webpack.config.js
=> [#OCD-2745] build: remove "UAT_MODE"

PENDING_RELEASE_NOTES.md, src/error.html, src/style.html, src/unsupported-browser.html
=> docs: confirm CHPL does not support IE

flags.development.json, flags.production.json, src/app/components/developer/developer.html, src/app/components/product/product.html, src/app/index.route.js, src/app/index.run.js, src/app/navigation/navigation-top.html, src/app/navigation/navigation.directive.js, src/app/pages/administration/administration.component.js, src/app/pages/administration/administration.html, src/app/pages/listing/listing.state.js, src/app/pages/organizations/organizations.state.js
Also updated the way the feature flags work
=> OCD 2756: Remove code/last modified date during split

flags.development.json, flags.production.json, src/app/index.run.js, src/app/pages/administration/administration.state.js, src/app/pages/organizations/organizations.state.js
Also sets state trail data as a flag
=> Handle problems related to minification of code

src/app/pages/administration/administration.module.js, yarn.lock
=> [#OCD-2866] fix: provide FileUpload service

src/app/pages/reports/developers.component.spec.js, src/app/pages/reports/listings.component.spec.js
=> OCD-2755 - Improve Reports responsiveness - save filter

src/app/admin/components/apiDocumentation/apiDocumentation.component.js, src/app/admin/components/surveillance/nonconformity/edit.component.js
=> [#OCD-2866] fix: show better error message on upload failure

FLAGGED_RELEASE_NOTES.md, PENDING_RELEASE_NOTES.md, flags.development.json, flags.production.json, src/app/pages/resources/overview/overview.html
@ashwinimore this does update the selectors to get them back in line and consistent
=> [#OCD-2894] feat: remove flag from Overview nav change

FLAGGED_RELEASE_NOTES.md, PENDING_RELEASE_NOTES.md, flags.development.json, flags.production.json, src/app/admin/components/schedules/schedules.directive.js
=> OCD-2871 - Scheduled Jobs list gets out of sync when deleting

src/app/admin/components/reports/filter.component.js, src/app/components/smart-table/chplSearch.directive.js, src/app/pages/reports/listings.component.js, src/app/pages/reports/listings.html, src/app/pages/reports/reports.state.js
fix: update listings report to switch between filters with productIds
fix: refresh filter list when user stops impersonating
=> OCD-2775- Improve Reports responsiveness - save filter

PENDING_RELEASE_NOTES.md, RELEASE_NOTES.md
=> docs: fix erroneous release notes

flags.development.json, flags.production.json
=> fix: remove obsolete flag

src/app/index.run.js, src/app/pages/listing/listing.state.js
=> fix: use states correctly based on flags

src/app/admin/components/reports/reports.component.js, src/app/admin/components/reports/reports.component.spec.js, src/app/admin/components/reports/reports.html
=> fix: remove last of old Reports

src/app/navigation/navigation-top.html
=> [#OCD-2752] feat: show carets for user reports

src/app/admin/components/reports/reports.component.spec.js, src/app/components/components.module.js, src/app/components/surveillance/complaint/complaint.component.js, src/app/components/surveillance/complaint/complaint.component.spec.js, src/app/components/surveillance/complaint/complaint.html, src/app/components/surveillance/report/report.component.spec.js, src/app/components/surveillance/surveillance/surveillance.component.spec.js, src/app/pages/reports/acbs/acbs.component.spec.js, src/app/pages/reports/announcements/announcements.component.spec.js, src/app/pages/reports/api-key-usage/api-key-usage.component.spec.js, src/app/pages/reports/api-keys/api-keys.component.spec.js, src/app/pages/reports/components/compare-surveillances.component.spec.js, src/app/pages/reports/components/filter.component.spec.js, src/app/pages/reports/developers/developers.component.spec.js, src/app/pages/reports/listings/listings.component.spec.js, src/app/pages/reports/products/products.component.spec.js, src/app/pages/reports/userActions/userActions.component.spec.js, src/app/pages/reports/users/users.component.spec.js, src/app/pages/surveillance/complaints/complaints.component.spec.js, src/app/pages/surveillance/confirm/surveillance.component.spec.js, src/app/services/network.service.spec.js
=> test: fix brokern tests and only run tests wrt to current development

src/app/pages/reports/userActions/userActions.component.js, src/app/pages/reports/userActions/userActions.html, src/app/pages/reports/users/users.component.js, src/app/pages/reports/users/users.html
fix: implement clear filter functionality
=> OCD-2789 - User reports 

src/app/index.run.js, src/app/navigation/navigation.directive.js
=> [#OCD-2745] fix: only toggle nav for logged in users

src/app/index.run.js
=> fix: load feature flags even if user not logged in

src/app/components/surveillance/complaint/complaint.html, src/app/pages/surveillance/complaints/complaints.component.js, src/app/pages/surveillance/complaints/complaints.html
=> Ocd 2912 - Add a basic complaint

src/app/navigation/navigation-top.html
=> feat: rearrange reports section of nav bar

src/app/pages/surveillance/reporting/reporting.html
=> feat: add styling

src/app/components/smart-table/chpl-surveillance-filter.html, src/app/pages/surveillance/surveillance.scss, src/app/pages/surveillance/surveillance/confirm.html, src/app/pages/surveillance/surveillance/manage.component.js, src/app/pages/surveillance/surveillance/manage.html
Almost all of the HTML changes are due to modifications of nesting. Sorry for all the diffs
=> [#OCD-1277] feat: update UX of surveillance management page

src/app/components/user/users.component.js, src/app/components/user/users.html, src/app/pages/users/management.component.js
=> feat: add user search capability

src/app/components/surveillance/complaint/complaint.component.js, src/app/components/surveillance/complaint/complaint.html, src/app/pages/surveillance/complaints/complaints.component.js, src/app/pages/surveillance/complaints/complaints.component.spec.js, src/app/pages/surveillance/complaints/complaints.html, src/app/services/network.service.js, src/app/services/network.service.spec.js
Fix order of fields, rename complaint type -> complainant type
=> Ocd 2912 - Create a basic caomplaint

src/app/components/surveillance/complaint/complaint.html, src/app/pages/surveillance/complaints/complaints.component.js, src/app/pages/surveillance/complaints/complaints.html
I'm not 100% sure that the date fix is going to work on DEV.
=> Ocd 2912 - Create a basic complaint

src/app/components/surveillance/reporting/annual.component.js, src/app/components/surveillance/reporting/annual.html, src/app/components/surveillance/reporting/quarter.component.js, src/app/components/surveillance/reporting/quarter.html, src/app/components/surveillance/reporting/relevant-listing.component.js, src/app/components/surveillance/reporting/relevant-listing.component.spec.js, src/app/components/surveillance/reporting/relevant-listing.html, src/app/pages/surveillance/reporting/reporting.component.js, src/app/pages/surveillance/reporting/reporting.html, src/app/services/network.service.js, src/app/services/network.service.spec.js
Can't merge until API is ready, but wanted to get it out here for that
=> OCD 2919 - relevant listings

src/app/components/surveillance/complaint/complaint.component.js
=> test: update tests so that they run with new criteria sorting

src/app/components/surveillance/complaint/complaint.component.js, src/app/components/surveillance/complaint/complaint.html, src/app/components/surveillance/complaint/complaint.scss, src/app/pages/surveillance/complaints/complaints.component.js
feat: prevent user from adding dup listing, survs, and criteria to cmpl
also:
* better display of mutli selected items
* use toaster to inidcate add/removal/dup of multi-select items
=> OCD-2913 - Associate a complaint with a listing

src/app/components/surveillance/complaint/complaint.component.js
fix: fix issue when removing criteria all criteria being removed
=> OCD-2914 - Associate complaint with criteria

src/app/components/surveillance/complaint/complaint.component.js, src/app/components/surveillance/complaint/complaint.html, src/app/pages/surveillance/complaints/complaints.component.js
=> fix: add debug information for date issues

src/app/components/surveillance/complaint/complaint.html
=> fix: add UTC formatting to dates

src/app/components/surveillance/complaint/complaint.component.js, src/app/components/surveillance/complaint/complaint.html, src/app/pages/surveillance/complaints/complaints.component.js
=> refactor: cleanup code from testing

src/app/pages/reports/announcements/announcements.component.js, src/app/pages/reports/announcements/announcements.html
=> Ocd 2754 - Improve Reports responsiveness - Announcements

src/app/pages/reports/announcements/announcements.component.js
feat: update how we are handling checking the Public flag
=> OCD-2754 - Improve Reports responsiveness - Announcements

src/app/pages/reports/developers/developers.html
=> fix: update developer activity report to display resp user on download

src/app/pages/reports/developers/developers.html
=> fix: fix responsible user display in CSV

src/app/components/surveillance/complaint/complaint.html, src/app/pages/surveillance/complaints/complaints.html
=> refactor: add IDs to requested elements for AQA purposes

src/app/pages/reports/announcements/announcements.html
=> fix: fix sorting on description column

src/app/components/announcement/announcement.component.js, src/app/components/announcement/announcement.component.spec.js, src/app/components/announcement/announcement.html, src/app/navigation/navigation-top.html, src/app/pages/administration/administration.state.js, src/app/pages/administration/announcements/announcements.component.js, src/app/pages/administration/announcements/announcements.component.spec.js, src/app/pages/administration/announcements/announcements.html, src/app/services/network.service.js
There was something in the code about managing deleted announcements. Is that a thing that we do? Didn't add anything for this PR, but want to make a note to see what's up with it
=> [#OCD-2966]feat: add announcement mgmt to new admin nav

src/app/components/surveillance/complaint/complaint.component.js, src/app/components/surveillance/complaint/complaint.html, src/app/components/surveillance/complaint/complaint.scss, src/app/pages/surveillance/complaints/complaints.html, src/app/pages/surveillance/reporting/reporting.html, src/app/pages/surveillance/reporting/reporting.scss
UI changes requested by Heather
=> OCD-2912 - Create a basic complaint

src/app/pages/surveillance/complaints/complaints.component.js
OCD-2912 - Create a basic complaint
=> fix: handle when "received date" is empty when saving

src/app/components/surveillance/complaint/complaint.html
=> fix: fix required validation of complaintant type

src/app/pages/surveillance/surveillance.state.js
=> fix: allow loading of page while needed API isn't ready

src/app/index.run.js, src/app/pages/organizations/onc-organizations/onc-organizations.component.js, src/app/pages/organizations/onc-organizations/onc-organizations.html, src/app/pages/organizations/organizations.state.js, src/app/pages/surveillance/surveillance.state.js, src/app/services/network.service.js, src/app/services/network.service.spec.js
Set up direct navigation to ACBs & ATLs, and improved the breadcrumbs
=> OCD 2747 ONC/ACB stuff

src/app/pages/surveillance/complaints/complaints.component.js, src/app/pages/surveillance/complaints/complaints.html, src/app/pages/surveillance/reporting/quarter.html
=> fix: hide delete complaint button on the quarter report

src/app/components/surveillance/complaint/complaint.component.spec.js
=> test: allow tests to compile / pass

src/app/pages/administration/administration.state.js
=> qa: call method correctly

src/app/pages/surveillance/reporting/annual.html, src/app/pages/surveillance/reporting/quarter.html, src/app/pages/surveillance/reporting/reporting.html
=> qa: change style of quarterly report

src/app/pages/surveillance/surveillance.scss, src/app/pages/surveillance/surveillance/components/view.html, src/app/pages/surveillance/surveillance/manage.component.js, src/app/pages/surveillance/surveillance/manage.html
=> flag: allow closing of tabs from header

src/app/components/user/users.html
=> qa: change layout of user management

src/app/components/user/users.html
=> ui: change button style

src/app/pages/administration/api-keys/api-keys.component.js, src/app/pages/administration/api-keys/api-keys.html, src/app/pages/administration/cms/cms.component.js, src/app/pages/administration/cms/cms.html, src/app/pages/administration/confirm/listings.html, src/app/pages/administration/fuzzy-matching/fuzzy-matching.component.js, src/app/pages/administration/fuzzy-matching/fuzzy-matching.html, src/app/pages/administration/jobs/background/page.component.js, src/app/pages/administration/jobs/background/page.html, src/app/pages/administration/jobs/scheduled/page.component.js, src/app/pages/administration/jobs/scheduled/page.html, src/app/pages/administration/jobs/scheduled/triggers.html, src/app/pages/administration/upload/upload.html
=> fix: show login widget when appropriate

src/app/components/announcement/announcement.html
=> qa: modify ids for announcements

src/app/pages/surveillance/surveillance.scss, src/app/pages/surveillance/surveillance/manage.component.js, src/app/pages/surveillance/surveillance/manage.html
=> ui: change styling on button

src/app/pages/surveillance/reporting/annual.html
=> ui: make button non-specific

src/app/pages/surveillance/reporting/quarter.html
=> ui: make button not specialized

src/app/components/surveillance/reporting/excluded-listings.component.js
=> qa: clear excluded listing from form on save

src/app/components/surveillance/complaint/complaint.html
=> QA: Update Complaint Summary required error message

src/app/components/user/users.html
=> fix: search for users correctly when table flag is off

src/app/index.js, src/app/index.route.js, src/app/index.run.js, src/app/pages/dashboard/dashboard.component.js, src/app/pages/dashboard/dashboard.component.spec.js, src/app/pages/dashboard/dashboard.html, src/app/pages/dashboard/dashboard.module.js, src/app/pages/dashboard/dashboard.state.js, src/app/pages/dashboard/index.js, src/app/services/network.service.js, src/app/services/network.service.spec.js, src/app/templates.js
Supports inviting a user to be ROLE_DEVELOPER, for a single hardcoded developer. Will need a lot of work before it can be really used, but functions as intended right now
[#OCD-2158]
=> flag: provide base "dashboard" page

src/index.html
=> ui: Turn off EDGE's telephone detection "feature"

src/app/pages/surveillance/reporting/reporting.component.js, src/app/pages/surveillance/reporting/reporting.component.spec.js, src/app/pages/surveillance/reporting/reporting.html
=> feat: disable annual generation unless quarter exists

src/app/components/smart-table/aiSurveillanceFilter.directive.js
=> fix:  Update surveillance filter to work correctly when navigating back to search

src/app/navigation/navigation-top.html, src/app/pages/surveillance/complaints/complaints.html, src/app/pages/surveillance/surveillance.state.js
=> ui: Change title of Complaints page

FLAGGED_RELEASE_NOTES.md, RELEASE_NOTES.md, src/app/admin/components/acb/view.html, src/app/admin/components/atl/view.html, src/app/admin/components/user/userManagement.component.js, src/app/components/user/users.html, src/app/index.run.js, src/app/navigation/navigation-top.html, src/app/pages/users/users.state.js
=> feat: Provide new UI/UX for user management

src/app/components/surveillance/reporting/relevant-listing.html, src/app/components/surveillance/reporting/relevant-listings.html, src/app/components/surveillance/reporting/relevant-surveillance.html
=> test: add IDs for various buttons

src/app/components/user/user.html
* Last Logged In Date
* Organization(s) user is associated with
OCD-3013
=> feat: Update user information to include:

src/app/admin/components/surveillance/nonconformity/edit.component.js, src/app/admin/components/surveillance/nonconformity/edit.html
=> qa: show filename and type in response

src/app/components/user/user.html
=> qa: Display orgs associated with a user in alphabetical order

src/app/pages/reports/api-key-usage/api-key-usage.html
[#OCD-2748]
Not entirely sure if this is going to work. Always challenges with timezones, especially between server and local, but need to get it out on DEV to test
=> qa: display time w/o timezone so it looks right

src/app/pages/reports/api-key-usage/api-key-usage.component.js, src/app/pages/reports/api-key-usage/api-key-usage.html
=> qa: add Download button for API Key Usage report

src/app/pages/reports/api-key-usage/api-key-usage.component.js, src/app/pages/reports/api-key-usage/api-key-usage.html, src/app/pages/reports/api-keys/api-keys.html, src/app/pages/reports/listings/listings.component.js, src/app/pages/reports/listings/listings.html, src/app/services/network.service.js
=> qa: improve filter for API Key usage report

src/app/pages/reports/api-key-usage/api-key-usage.html
=> qa: use last four instead of first four characters

src/app/components/surveillance/reporting/relevant-listing.html
=> qa: add link to surveillance editing

FLAGGED_RELEASE_NOTES.md, src/app/components/developer/developer.html, src/app/index.run.js, src/app/navigation/navigation-top.html, src/app/pages/organizations/organizations.state.js
* Complete change / upgrade of ONC-ACB and ONC-ATL management screens
* Add new Organizations - Developer page
* Includes support for Edit, Merge, Split
* Add support for Product editing on new Organizations - Developer page
* Includes Edit, Merge, and Split
* Add support for Version editing on new Org - Dev - Product page
* Includes Edit, Merge, and Split
[#OCD-2747]
=> feat: Add new "Organizations" nav item for logged in users

src/app/components/user/user.html
=> ui: Improve display of User Organizations

RELEASE_NOTES.md
=> docs: add missed release note item

src/app/components/surveillance/complaint/complaint.html, src/app/components/surveillance/reporting/relevant-listing.component.js, src/app/components/surveillance/reporting/relevant-listing.component.spec.js, src/app/components/surveillance/reporting/relevant-listing.html, src/app/components/surveillance/reporting/relevant-listings.component.js, src/app/pages/surveillance/reporting/quarter.component.js, src/app/pages/surveillance/reporting/quarter.html, src/app/pages/surveillance/surveillance.state.js
PR title is because that change will be displayed to end users, so should go in RELEASE_NOTES. The vast majority of this PR is related to a new workflow for editing Surveillances from the reporting screen. 
Also includes a tweak to the wording of one reference document
=> ui: Standardize button display on complaints

src/app/navigation/navigation-top.html, src/app/pages/reports/reports.state.js
=> style: use standards for states

src/app/components/surveillance/reporting/relevant-listing.component.js, src/app/pages/surveillance/reporting/quarter.component.js
=> qa: reload relevant survs after surv data edit

src/app/pages/reports/developers/developers.html
=> fix: Added Details column and merge, split activity details

src/app/pages/registration/create-user.html
=> ui: Update sign up text to support Developers

FLAGGED_RELEASE_NOTES.md, RELEASE_NOTES.md
=> docs: insert missed release note item

src/app/pages/registration/create-user.html
=> ui: change wording on user creation workflow

src/app/components/onc-organization/onc-organization-edit.html, src/app/navigation/navigation-top.html, src/app/pages/organizations/onc-organizations/onc-organizations.html
=> test: modify IDs for easier testing

src/app/admin/components/certifiedProduct/listing/edit.html, src/app/components/listing/edit.html
=> flag: Require reason for editing of 2014 listing

src/app/pages/reports/products/products.component.js, src/app/pages/reports/products/products.html
=> fix: Add missing Product activity data to downloadable file

src/app/components/listing/inspect/inspect.controller.js, src/app/components/listing/inspect/inspect.html
=>  fix: Enable next for new developer and add error reporting

FLAGGED_RELEASE_NOTES.md, RELEASE_NOTES.md
=> docs: reconcile RELEASE_NOTES

src/app/pages/administration/jobs/scheduled/trigger.html
=> feat: Allow jobs to display text, date, and select for additional job data

src/app/index.run.js, src/app/navigation/navigation-top.html, src/app/pages/surveillance/surveillance.state.js
=> flag: remove "complaints" flag, leaving feature enabled

src/app/components/cms-widget/cms-widget.directive.js
=> flag: build CMS ID report with new 2015 criteria reqs

src/app/components/user/users.html
=> flag: remove unused flag

src/app/index.run.js, src/app/navigation/navigation-top.html, src/app/pages/surveillance/surveillance.state.js
=> flag: remove "surveillance-reporting" flag

src/app/components/surveillance/complaint/complaint.component.js, src/app/components/surveillance/complaint/complaint.component.spec.js, src/app/components/surveillance/complaint/complaint.html, src/app/pages/surveillance/complaints/complaints.component.js, src/app/pages/surveillance/complaints/complaints.component.spec.js, src/app/pages/surveillance/complaints/complaints.html, src/app/services/network.service.js, src/app/services/network.service.spec.js
=> OCD-3116 - feat!: Make Complaint Status Type a result of close date existence

src/app/components/listing/details/criteria/edit.html
=> fix: Remove the max-length constraint from the Alteration input text field

src/app/admin/components/certifiedProduct/management.directive.js
=> feat!: Allow Admin/ONC users to edit listing if developer is banned

src/app/pages/collections/collection.directive.js, src/app/pages/collections/collections.service.js, src/app/pages/collections/inactive/inactive.controller.js, src/app/pages/collections/inactive/inactive.html
=> feat-flag!: Update text on Inactive Collections page

src/app/admin/components/certifiedProduct/management.directive.js, src/app/admin/components/certifiedProduct/management.html
=> Ocd 3218 - Fix display of TAs on the listing management page

src/app/index.scss, src/app/pages/reports/listings/listings.component.js, src/app/pages/reports/listings/listings.html, src/app/pages/reports/listings/listings.scss
=> [#OCD-3255] feat-flag!: Allow different display of Listings report

src/app/pages/reports/acbs/acbs.html, src/app/pages/reports/announcements/announcements.html, src/app/pages/reports/api-key-usage/api-key-usage.html, src/app/pages/reports/api-keys/api-keys.html, src/app/pages/reports/atls/atls.html, src/app/pages/reports/developers/developers.html, src/app/pages/reports/listings/listings-legacy.html, src/app/pages/reports/listings/listings.html, src/app/pages/reports/products/products.html, src/app/pages/reports/user-actions/user-actions.html, src/app/pages/reports/users/users.html, src/app/pages/reports/versions/versions.html, src/app/services/util.service.js
OCD-3222
feat: Mark downloadable CSVs in a way that matches what Excel is expecting
=> OCD-3222: add BOM to allow for display of extended characters in CSV files

src/app/components/listing/details/criteria/edit.html
=> OCD-3245: Only display test functionality control if there are options

src/app/navigation/navigation-bottom.html
[#cures]
Temporary debugging stuff to help users know the state of the system wrt ERD date. Will be removed before actual ERD
=> feat: indicate status of system wrt ERD

src/app/components/change-request/change-request.component.spec.js, src/app/components/change-request/change-requests.component.js, src/app/components/change-request/change-requests.component.spec.js
No actual change in functionality, so will merge this in when it's approved
=> OCD-3197: fix failing tests; add test coverage

src/app/components/change-request/change-requests.component.js, src/app/components/change-request/change-requests.component.spec.js, src/app/services/login.service.js
=> [#OCD-3295] feat!: Only allow ROLE_DEVELOPER to withdraw a Change Request

src/app/pages/listing/history/history.component.js, src/app/pages/reports/listings/listings.component.js
=> OCD-3329 - Activity in product history and activity report does not show correct for criteria edits during listing edit

src/app/pages/charts/charts.html, src/app/pages/collections/collection.html, src/app/pages/compare/compare.html, src/app/pages/listing/listing.html, src/app/pages/reports/reports.html, src/app/pages/resources/chpl-api/chpl-api.html, src/app/pages/resources/cms-lookup/cms-lookup.html, src/app/pages/resources/download/download.html, src/app/pages/resources/overview/overview.html, src/app/pages/search/search.html, src/app/pages/surveillance/surveillance.html, src/app/pages/users/management.html
=> fix: remove over-enthusiastically applied styles

src/app/pages/search/search.html
=> [#OCD-3357] feat-flag!: Update text on main search page to reflect post effective-rule-date changes

src/app/components/listing/details/criteria/edit.component.js, src/app/components/listing/details/criteria/edit.html, src/app/components/listing/edit.component.js, src/app/components/listing/edit.component.spec.js, src/app/components/listing/inspect/inspect.controller.js, src/app/components/listing/inspect/inspect.controller.spec.js, src/app/components/util/expandable-list.component.js
=> [#OCD-3305] fix!: Only display applicable Test Standards in upload/confirm edit workflow

package.json
=> build: resolve issue with updated node
